title = "OpenNpc"  # From Git
gitRepoUrl = "" # From Git

gitSourceBranch = "master"
changelog = true
classOrder = []

[docusaurus]
onBrokenLinks = "throw"
onBrokenMarkdownLinks = "warn"
favicon = "https://eryn.io/moonwave/img/logo.svg"

# From git:
organizationName = "OpenFeline"
projectName = "OpenNpc"
url = "https://openfeline.github.io"
baseUrl = "/OpenNpc"
tagline = "A feline orientated npc controller."

[footer]
style = "dark"
copyright = "Copyright Â© 2026 OpenFeline. Built with Moonwave and Docusaurus"
