# This file lists tools managed by Rokit, a toolchain manager for Roblox projects.
# For more information, see https://github.com/rojo-rbx/rokit

# New tools can be added by running `rokit add <tool>` in a terminal.

[tools]
rojo = "rojo-rbx/rojo@7.6.1"
pesde = "pesde-pkg/pesde@0.7.2+registry.0.2.3"
StyLua = "JohnnyMorganz/StyLua@2.3.1"
selene = "Kampfkarren/selene@0.29.0"
lune = "lune-org/lune@0.10.4"
luau-lsp = "JohnnyMorganz/luau-lsp@1.60.1"
